### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by Gamgie** [jonglissimo/td-osc-query-server#1]
Hi ! 
If I add the tox to my project, every time I save my project, i've got an error. 

![image](https://user-images.githubusercontent.com/4440017/99197111-b9264900-2790-11eb-81bc-7bdbf8df2ab6.png)

I hope you'll find a solution. Thanks !

**Comment by manuelmitasch** [comment]
I fixed the save error and pushed a new version.

The component stores data in the python storage. Some of that data includes TD parameters. Some of the data was not cleared when the linked components were changed, thus it could not serialize the data and result in the pickle error on save. That should now be fixed in a robust way.
Thanks for reporting this!
